contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/CodeDredd/pinia-orm/discussions
    about: Ask a question or discuss about Pinia ORM
  - name: ğŸ“š Documentation
    url: https://pinia-orm.codedredd.de/
    about: Check the documentation for usage of Pinia ORM
  - name: â¤ GitHub Sponsors
    url: https://github.com/sponsors/codedredd
    about: Like this project? Please consider supporting the author.
